<!DOCTYPE testSuite [
<!ELEMENT testSuite (dataCategory)+>
<!ATTLIST testSuite xmlns CDATA #FIXED "http://example.com/myns">
<!ELEMENT dataCategory (inputfile+)>
<!ATTLIST dataCategory name CDATA #REQUIRED>
<!ELEMENT inputfile (description, expectedOutput, outputImplementors*)>
<!ATTLIST inputfile location CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT expectedOutput EMPTY>
<!ATTLIST expectedOutput location CDATA #REQUIRED>
<!ELEMENT outputImplementors EMPTY>
<!ATTLIST outputImplementors implementer (adobe|cocomore|dcu|enlaso|jsi|linguaserve|logrus|lucysoftware|moravia|shaun|tcd|tilde|ul|vistatec) #REQUIRED
location CDATA #REQUIRED>
]>
<testSuite xmlns="http://example.com/myns">

   <!--Translate-->   
   <dataCategory name="Translate">
      <inputfile location="inputdata/translate/xml/translate1xml.xml">
         <description>Global - Embeddedz rules</description>
         <expectedOutput location="expected/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate1xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate1xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate7html.html">
         <description>Global - Embedded rules &lt;its:param&gt;</description>
         <expectedOutput location="expected/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate7htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate7htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate9xml.xml">
         <description>Global - Embedded rules &lt;its:param&gt;</description>
         <expectedOutput location="expected/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate9xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate9xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate2xml.xml">
         <description>Global - Linked rules</description>
         <expectedOutput location="expected/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate2xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate2xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate10xml.xml">
         <description>Global - Linked rules&lt;its:param&gt;</description>
         <expectedOutput location="expected/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate10xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate10xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate1html.html">
         <description>Global - Linked rules</description>
         <expectedOutput location="expected/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate1htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate1htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate6html.html">
         <description>Global - Linked rules &lt;its:param&gt;</description>
         <expectedOutput location="expected/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate6htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate6htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate3xml.xml">
         <description>Global - Embedded and linked rules</description>
         <expectedOutput location="expected/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate3xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate3xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate4xml.xml">
         <description>Local - In host element</description>
         <expectedOutput location="expected/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate4xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate4xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate2html.html">
         <description>Local - In host element</description>
         <expectedOutput location="expected/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate2htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate2htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate5xml.xml">
         <description>Local - In &lt;its:span&gt;</description>
         <expectedOutput location="expected/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate5xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate5xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate6xml.xml">
         <description>Global (with //*) and local rules</description>
         <expectedOutput location="expected/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate6xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate6xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate3html.html">
         <description>Global (with //*) and local rules</description>
         <expectedOutput location="expected/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate3htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate3htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate7xml.xml">
         <description>Global (with /doc) and local rules</description>
         <expectedOutput location="expected/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate7xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate7xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate4html.html">
         <description>Global (with /doc) and local rules</description>
         <expectedOutput location="expected/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate4htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate4htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/xml/translate8xml.xml">
         <description>Global and local rules (inheritance)</description>
         <expectedOutput location="expected/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/xml/translate8xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/translate/xml/translate8xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/translate/html/translate5html.html">
         <description>Global and local rules (inheritance)</description>
         <expectedOutput location="expected/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="dcu" location="outputimplementors/dcu/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/translate/html/translate5htmloutput.txt"/>
         <outputImplementors implementer="lucysoftware" location="outputimplementors/lucysoftware/translate/html/translate5htmloutput.txt"/>
      </inputfile>
   </dataCategory>

   <!--Localization Note-->
   <dataCategory name="Localization Note">
      <inputfile location="inputdata/localizationnote/xml/locnote1xml.xml">
         <description>Global - Embedded rules with locNote</description>
         <expectedOutput location="expected/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote1xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote1xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote1html.html">
         <description>Global - Linked rules with locNote</description>
         <expectedOutput location="expected/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote1htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote1htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote2xml.xml">
         <description>Global - Embedded rules with locNotePointer</description>
         <expectedOutput location="expected/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote2xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote2xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote2html.html">
         <description>Global - Linked rules with locNotePointer</description>
         <expectedOutput location="expected/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote2htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote2htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote3xml.xml">
         <description>Global - Embedded rules with locNoteRef</description>
         <expectedOutput location="expected/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote3xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote3xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote3html.html">
         <description>Global - Linked rules with locNoteRef</description>
         <expectedOutput location="expected/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote3htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote3htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote4xml.xml">
         <description>Global - Embedded rules with locNoteRefPointer</description>
         <expectedOutput location="expected/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote4xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote4xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote4html.html">
         <description>Global - Linked rules with locNoteRefPointer</description>
         <expectedOutput location="expected/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote4htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote4htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote5xml.xml">
         <description>Global - Linked rules with locNote</description>
         <expectedOutput location="expected/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote5xmloutput.txt"/>
         <outputImplementors implementer="adobe" location="outputimplementors/adobe/localizationnote/xml/locnote5xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote5html.html">
         <description>Global - Linked rules with locNote</description>
         <expectedOutput location="expected/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote5htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote5htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote6xml.xml">
         <description>Global - Embedded rules with mixed notes</description>
         <expectedOutput location="expected/localizationnote/xml/locnote6xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote6xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote6xmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/xml/locnote6xmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/xml/locnote6xmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/html/locnote6html.html">
         <description>Global - Linked rules with mixed notes</description>
         <expectedOutput location="expected/localizationnote/html/locnote6htmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/html/locnote6htmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/html/locnote6htmloutput.txt"/>
         <outputImplementors implementer="shaun" location="outputimplementors/shaun/localizationnote/html/locnote6htmloutput.txt"/>
         <outputImplementors implementer="cocomore" location="outputimplementors/cocomore/localizationnote/html/locnote6htmloutput.txt"/>
         <outputImplementors implementer="linguaserve" location="outputimplementors/linguaserve/localizationnote/html/locnote6htmloutput.txt"/>
      </inputfile>
      <inputfile location="inputdata/localizationnote/xml/locnote7xml.xml">
         <description>Local - In host element with locNote</description>
         <expectedOutput location="expected/localizationnote/xml/locnote7xmloutput.txt"/>
         <outputImplementors implementer="enlaso" location="outputimplementors/enlaso/localizationnote/xml/locnote7xmloutput.txt"/>
         <outputImplementors implementer="ul" location="outputimplementors/ul/localizationnote/xml/locnote7xmloutput.txt"/>